### PR TITLE
In-memory shading

### LINKED ISSUE #38: Run CLI on Shapeless
## steps

```python
scala_import(
  name = "jar",
  tags = ["maven_coordinates=com.chuusai:shapeless_2.12", "maven_coordinates_and_version=com.chuusai:shapeless_2.12:2.3.2"],
  jars = ["@jvm__com_chuusai__shapeless//:shapeless_2.12.jar"],
  deps = [],
  exports = ["@jvm__org_scala_lang__scala_library//:jar", "@jvm__org_typelevel__macro_compat//:jar"],
  srcjar = "@jvm__com_chuusai__shapeless//:shapeless_2.12-sources.jar",
)
```

## Problem

We're seeing this on Jenkins:

```scala
13:54:23 2023-10-04 17:54:23 Syntax error: Malformed input or input contains unmappable characters: shapeless/$tilde$qmark$greater$?.class
13:54:23 2023-10-04 17:54:23 Exception in thread "main" java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: shapeless/$tilde$qmark$greater$?.class
13:54:23 2023-10-04 17:54:23 at sun.nio.fs.UnixPath.encode(UnixPath.java:145)
13:54:23 2023-10-04 17:54:23 at sun.nio.fs.UnixPath.<init>(UnixPath.java:69)
13:54:23 2023-10-04 17:54:23 at sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:279)
13:54:23 2023-10-04 17:54:23 at java.nio.file.Path.resolve(Path.java:515)
13:54:23 2023-10-04 17:54:23 at com.eed3si9n.jarjarabrams.Zip$.next$1(Zip.scala:167)
13:54:23 2023-10-04 17:54:23 at com.eed3si9n.jarjarabrams.Zip$.extract(Zip.scala:188)
13:54:23 2023-10-04 17:54:23 at com.eed3si9n.jarjarabrams.Zip$.$anonfun$unzipStream$1(Zip.scala:153)
13:54:23 2023-10-04 17:54:23 at com.eed3si9n.jarjarabrams.Using.apply(Using.scala:22)
13:54:23 2023-10-04 17:54:23 at com.eed3si9n.jarjarabrams.Zip$.unzipStream(Zip.scala:153)
13:54:23 2023-10-04 17:54:23 at com.eed3si9n.jarjarabrams.Zip$.$anonfun$unzip$1(Zip.scala:24)
13:54:23 2023-10-04 17:54:23 at com.eed3si9n.jarjarabrams.Using.apply(Using.scala:22)
13:54:23 2023-10-04 17:54:23 at com.eed3si9n.jarjarabrams.Zip$.unzip(Zip.scala:24)
13:54:23 2023-10-04 17:54:23 at com.eed3si9n.jarjarabrams.Shader$.shadeFile(Shader.scala:20)
13:54:23 2023-10-04 17:54:23 at com.eed3si9n.jarjarabrams.Main.process(Main.scala:21)
13:54:23 2023-10-04 17:54:23 at java.lang.reflect.Method.invoke(Method.java:566)
13:54:23 2023-10-04 17:54:23 at com.eed3si9n.jarjar.MainUtil.runMain(MainUtil.java:39)
13:54:23 2023-10-04 17:54:23 at com.eed3si9n.jarjarabrams.Main$.main(Main.scala:27)
13:54:23 2023-10-04 17:54:23 at com.eed3si9n.jarjarabrams.Main.main(Main.scala)
```

### PR DESCRIPTION
**Pull request by eed3si9n**
Fixes https://github.com/eed3si9n/jarjar-abrams/issues/38

## Problem

File name entry encoding issue.

## Solution

1. Generally use `JarOutputStream` or Jar* series of streams instead of Zip*. This is because PKWare spec says that the file names should be encoded using IBM Code Page 437, but JARs use UTF-8. JDK 7 adds a parameter to workaround this but generally JAR isn't ZIP in these details.
2. Avoid unjarring, and perform in-memory shading. This would avoid the Unix path having issues with arbitrary string being a path.

### CODE REVIEW

File: core/src/main/scala/com/eed3si9n/jarjarabrams/Zip.scala [hunk 1]
```diff
@@ -1,192 +1,134 @@
...
+  // Archive:  example/byte-buddy-agent.jar
+  //   Length      Date    Time    Name
+  // ---------  ---------- -----   ----
+  //         0  00-00-1980 04:08   META-INF/
+  //       988  00-00-1980 04:08   META-INF/MANIFEST.MF
+  private final val minimumTimestamp = 315705600L
+
+  def list(inputJar: Path): List[(String, Long)] =
+    Using.jarFile(inputJar) { in =>
+      in.entries.asScala.toList.map { entry =>
```
Comment (johnynek) [inline core/src/main/scala/com/eed3si9n/jarjarabrams/Zip.scala]: Nit: I would do

`.asScala.iterator.map(...).toList`

To avoid allocating an intermediate List.

File: core/src/main/scala/com/eed3si9n/jarjarabrams/Zip.scala [hunk 2]
```diff
@@ -1,192 +1,134 @@
...
-            case NonFatal(e) =>
-              throw new RuntimeException(
-                "error extracting Zip entry '" + name + "' to '" + target + "'",
-                e
-              )
+  /**
+   * Treating JAR file as a set of EntryStruct, this implements a
+   * functional processing, intended for in-memory shading.
+   */
+  def flatMap(
```
Comment (johnynek) [inline core/src/main/scala/com/eed3si9n/jarjarabrams/Zip.scala]: I'm pretty negative on this name. I'm a bit of a flatMap-means-monad guy personally and this is pretty far from.

What about `def maybeTransformEntries` or rewriteOption or something.

File: core/src/main/scala/com/eed3si9n/jarjarabrams/Zip.scala [hunk 3]
```diff
@@ -1,192 +1,134 @@
...
+  )(f: EntryStruct => Option[EntryStruct]): Path =
+    Using.jarFile(inputJar) { in =>
+      val tempJar = Files.createTempFile("jarjar", ".jar")
+      val names = new mutable.HashSet[String]
+      Using.jarOutputStream(tempJar) { out =>
+        in.entries.asScala.toList.foreach { entry0 =>
+          val struct0 = entryStruct(
+            entry0.getName,
+            entry0.getTime, {
+              val baos = new ByteArrayOutputStream()
```
Comment (johnynek) [inline core/src/main/scala/com/eed3si9n/jarjarabrams/Zip.scala]: Can we just make a little private def that's like InputStream to Array[Byte] rather than the nested inline of it here?

File: core/src/main/scala/com/eed3si9n/jarjarabrams/Zip.scala [hunk 4]
```diff
@@ -1,192 +1,134 @@
...
+   * functional processing, intended for in-memory shading.
+   */
+  def flatMap(
+      inputJar: Path,
+      outputJar: Path,
+      resetTimestamp: Boolean
+  )(f: EntryStruct => Option[EntryStruct]): Path =
+    Using.jarFile(inputJar) { in =>
+      val tempJar = Files.createTempFile("jarjar", ".jar")
+      val names = new mutable.HashSet[String]
```
Comment (johnynek) [inline core/src/main/scala/com/eed3si9n/jarjarabrams/Zip.scala]: Not: move this inside the following Using since it is local to that function and won't need a closure then.

**Review by johnynek — COMMENTED** [review]
A few suggestions.

Thanks for doing this. Excited to reduce duplication or jarjar implementations and for the improved testing.

I wonder if you have any ideas for how we could set up CI to test with more than one time zone to verify that resulting shaded jars are time zone independent.

File: core/src/main/scala/com/eed3si9n/jarjarabrams/Zip.scala (hunk 1 above)
Comment (eed3si9n) [reply core/src/main/scala/com/eed3si9n/jarjarabrams/Zip.scala]: Addressed in https://github.com/eed3si9n/jarjar-abrams/pull/39/commits/d41bfc7e682966948cea777d4cbe8e9db4ca1b65

File: core/src/main/scala/com/eed3si9n/jarjarabrams/Zip.scala (hunk 2 above)
Comment (eed3si9n) [reply core/src/main/scala/com/eed3si9n/jarjarabrams/Zip.scala]: Yea, I knew it wasn't really `flatMap` but it's a good mental approximation to think of it as such. Renamed to `transformJarFile` in https://github.com/eed3si9n/jarjar-abrams/pull/39/commits/d41bfc7e682966948cea777d4cbe8e9db4ca1b65.

File: core/src/main/scala/com/eed3si9n/jarjarabrams/Zip.scala (hunk 3 above)
Comment (eed3si9n) [reply core/src/main/scala/com/eed3si9n/jarjarabrams/Zip.scala]: Done in https://github.com/eed3si9n/jarjar-abrams/pull/39/commits/d41bfc7e682966948cea777d4cbe8e9db4ca1b65

File: core/src/main/scala/com/eed3si9n/jarjarabrams/Zip.scala (hunk 4 above)
Comment (eed3si9n) [reply core/src/main/scala/com/eed3si9n/jarjarabrams/Zip.scala]: Done in https://github.com/eed3si9n/jarjar-abrams/pull/39/commits/d41bfc7e682966948cea777d4cbe8e9db4ca1b65

File: core/src/main/scala/com/eed3si9n/jarjarabrams/Zip.scala [hunk 5]
```diff
@@ -1,192 +1,131 @@
...
+  def transformJarFile(
+      inputJar: Path,
+      outputJar: Path,
+      resetTimestamp: Boolean
+  )(f: EntryStruct => Option[EntryStruct]): Path =
+    Using.jarFile(inputJar) { in =>
+      val tempJar = Files.createTempFile("jarjar", ".jar")
+      Using.jarOutputStream(tempJar) { out =>
+        val names = new mutable.HashSet[String]
+        in.entries.asScala.toList.foreach { entry0 =>
```
Comment (johnynek) [inline core/src/main/scala/com/eed3si9n/jarjarabrams/Zip.scala]: Why toList if we only need foreach? Seems like asScala.foreach would do, no?

File: core/src/main/scala/com/eed3si9n/jarjarabrams/Zip.scala [hunk 6]
```diff
@@ -1,192 +1,131 @@
...
+              if (names.add(struct.name)) {
+                val entry = new JarEntry(struct.name)
+                val time =
+                  if (resetTimestamp) hardcodedZipTimestamp(struct.name)
+                  else enforceMinimum(struct.time)
+                entry.setTime(time)
+                entry.setCompressedSize(-1)
+                out.putNextEntry(entry)
+                out.write(struct.data)
+              } else if (struct.name.endsWith("/")) ()
```
Comment (johnynek) [inline core/src/main/scala/com/eed3si9n/jarjarabrams/Zip.scala:73]: Should this not be first? Not sure why it is here actually. The else of this if is also returning ()

File: core/src/main/scala/com/eed3si9n/jarjarabrams/Zip.scala [hunk 7]
```diff
@@ -1,192 +1,131 @@
...
+   * functional processing, intended for in-memory shading.
+   */
+  def transformJarFile(
+      inputJar: Path,
+      outputJar: Path,
+      resetTimestamp: Boolean
+  )(f: EntryStruct => Option[EntryStruct]): Path =
+    Using.jarFile(inputJar) { in =>
+      val tempJar = Files.createTempFile("jarjar", ".jar")
+      Using.jarOutputStream(tempJar) { out =>
```
Comment (johnynek) [inline core/src/main/scala/com/eed3si9n/jarjarabrams/Zip.scala:53]: Why write into one jar then copy vs just write directly into the output?

Or write into a file and then on success mv it (which will often be almost free and atomic).

**Review by johnynek — APPROVED** [review]
A few more questions that maybe we can address later if you want.

File: core/src/main/scala/com/eed3si9n/jarjarabrams/Zip.scala (hunk 6 above)
Comment (eed3si9n) [reply core/src/main/scala/com/eed3si9n/jarjarabrams/Zip.scala:73]: I think we do want entries that ends with `/` to transform like `shapeless/` becomes `foo/shapeless`. The original `else if` in Java code exempts directories from duplicate entry exception. If we ignore the duplicate entry exception, like I am doing here, then this clause is meaningless.

File: core/src/main/scala/com/eed3si9n/jarjarabrams/Zip.scala (hunk 5 above)
Comment (eed3si9n) [reply core/src/main/scala/com/eed3si9n/jarjarabrams/Zip.scala]: I was being paranoid of the laziness of the iterator. I guess `foreach` would trigger, so I can drop `toList`.

File: core/src/main/scala/com/eed3si9n/jarjarabrams/Zip.scala [hunk 8]
```diff
@@ -189,4 +190,23 @@ object Zip {
   def createDirectories(p: Path): Unit =
     if (Files.exists(p)) ()
     else Files.createDirectories(p)
+
+  def sha256(p: Path): String =
+    Using.fileInputStream(p) { in =>
+      val digest = MessageDigest.getInstance("SHA-256")
+      val hash = digest.digest(toByteArray(in))
```
Comment (johnynek) [inline core/src/main/scala/com/eed3si9n/jarjarabrams/Zip.scala]: I wouldn't do this. What about:

https://docs.oracle.com/javase/8/docs/api/java/security/DigestInputStream.html

then use transfer with a no-op outputstream. No need to keep the whole file in memory just to hash.

**Comment by eed3si9n** [comment]
@johnynek 

> I wonder if you have any ideas for how we could set up CI to test with more than one time zone to verify that resulting shaded jars are time zone independent.

sha256 might be a blunt hammer to check this, but it shows that I still have some stability issue:

```
[info]   assert(actualSha == expectedSha)
[info]          |         |  |
[info]          |         |  6e7372e52e3b2e981ffa42fc29d5cec1cc84431972d45fb51d605210e11c3ebd
[info]          |         false
[info]          038a68df151fc1549c487d79a5ae8ed5a1c2ff3f6ccbee2953f35bfc736b6e83
```

I don't think it's quite enforcing the minimal timestamp yet.

File: core/src/main/scala/com/eed3si9n/jarjarabrams/Zip.scala [hunk 9]
```diff
@@ -30,7 +30,7 @@ object Zip {
   // ---------  ---------- -----   ----
   //         0  00-00-1980 04:08   META-INF/
   //       988  00-00-1980 04:08   META-INF/MANIFEST.MF
-  private final val minimumTimestamp = 315705600L
+  private final val minimumTimestamp = 315705600000L
```
Comment (eed3si9n) [inline core/src/main/scala/com/eed3si9n/jarjarabrams/Zip.scala:33]: I was off by 1000x (milisec).

File: core/src/test/scala/testpkg/ShaderTest.scala [hunk 10]
```diff
@@ -65,6 +66,8 @@ object ShaderTest extends BasicTestSuite {
     )
     val entries = Zip.list(tempJar).map(_._1)
     assert(entries.contains(expectedClass))
+    val lines = Process(s"unzip -l $tempJar").!!.linesIterator.toList.take(10)
+    lines.foreach(println)
```
Comment (johnynek) [inline core/src/test/scala/testpkg/ShaderTest.scala]: can we remove now?

File: core/src/main/scala/com/eed3si9n/jarjarabrams/Zip.scala (hunk 8 above)
Comment (johnynek) [reply core/src/main/scala/com/eed3si9n/jarjarabrams/Zip.scala]: or just move it to the test code that uses it. I don't mind an inefficient implementation that is just for test.

File: core/src/main/scala/com/eed3si9n/jarjarabrams/Zip.scala (hunk 5 above)
Comment (eed3si9n) [reply core/src/main/scala/com/eed3si9n/jarjarabrams/Zip.scala]: This was fixed in 0c2d4a01846bba8081b272b2dc28af1fb3edb3d0

File: core/src/main/scala/com/eed3si9n/jarjarabrams/Zip.scala (hunk 8 above)
Comment (eed3si9n) [reply core/src/main/scala/com/eed3si9n/jarjarabrams/Zip.scala]: Addressed in 7204aea1b5b2610d85c09e66896b08bd4adbe5c6

**Review by johnynek — APPROVED** [review]
When green let's merge!

File: core/src/main/scala/com/eed3si9n/jarjarabrams/Zip.scala (hunk 7 above)
Comment (eed3si9n) [reply core/src/main/scala/com/eed3si9n/jarjarabrams/Zip.scala:53]: Addressed in d368596fa0381745d1db9a0cf0ac80ef091f0947
